### PR TITLE
Adjusting storage request in KafkaCluster BrokerConfig does not updat…

### LINKED ISSUE #346: Adjusting storage request in KafkaCluster BrokerConfig does not update PVC
**Describe the bug**
Adjusting the storage request in the brokerConfigGroups default storageConfigs does not update PVCs that have already been created

**Steps to reproduce the issue:**
Create a KafkaCluster with something like this:
```
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafka
spec:
...
  brokerConfigGroups:
    default:
...
      storageConfigs:
        - mountPath: "/kafka-logs"          
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: 'gp2wfc'
...
```

After the cluster has been created, and everything is stable, update the configuration to increase the storage request, e.g.  
```
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafka
spec:
...
  brokerConfigGroups:
    default:
...
      storageConfigs:
        - mountPath: "/kafka-logs"          
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 40Gi
            storageClassName: 'gp2wfc'
...
```

**Expected behavior**
I expected the PVCs which got created along with the cluster to update their capacity (which can be done online as of Kubernetes 1.15 https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-a-volume-containing-a-file-system). Instead, the cluster seemed to do a rolling restart, but the PVCs did not change their capacity.

**Additional context**
Manually resizing the PVCs worked just fine, so it's an easy enough workaround.

### PR DESCRIPTION
**Pull request by schultheiszn**
…e PVC

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #346 
| License         | Apache 2.0

### What's in this PR?
Sync the current and the desired state if one changes the storageConfig

### Checklist

- [X] Implementation tested
- [X] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)

### CODE REVIEW

File: pkg/resources/kafka/kafka.go [hunk 1]
```diff
@@ -851,3 +860,7 @@ func GetBrokersWithPendingOrRunningCCTask(kafkaCluster *v1beta1.KafkaCluster) []
 	}
 	return brokerIDs
 }
+
+func isDesiredStorageValueInvalid(desired, current *corev1.PersistentVolumeClaim) bool {
+	return desired.Spec.Resources.Requests.Storage().Value() <= current.Spec.Resources.Requests.Storage().Value()
```
Comment (stoader) [inline pkg/resources/kafka/kafka.go:865]: I think this should rather be `<` as not changing the size is valid.

File: pkg/resources/kafka/kafka.go [hunk 2]
```diff
@@ -802,7 +802,16 @@ func (r *Reconciler) reconcileKafkaPvc(log logr.Logger, brokersDesiredPvcs map[s
...
 						return errors.WrapIf(err, "could not apply last state to annotation")
 					}
-					desiredPvc = currentPvc
+
+					if isDesiredStorageValueInvalid(desiredPvc, currentPvc) {
+						return errorfactory.New(errorfactory.InternalError{}, nil, "one can not reduce the size of a PVC", "kind", desiredType)
+					}
+
+					storageSize := desiredPvc.Spec.Resources.Requests.Storage().Value()
+					// because we are using generated names
```
Comment (stoader) [inline pkg/resources/kafka/kafka.go:811]: wouldn't `desiredopvc = currentPvc.DeepCopy()` copy all fields?

Comment (baluchicken) [reply pkg/resources/kafka/kafka.go:811]: I don't think we need DeepCopy, I think copying spec is enough.
