### PR TITLE
Fix: recreate evicted pod as well

### LINKED ISSUE #326: Evicted pods are not recreated
**Describe the bug**
Two of three kafka broker pods have been evicted by kubernetes. Operator leaves the cluster in this state (one broker running, two down) instead of recreating the evicted pods.

**Steps to reproduce the issue:**
Create a cluster with 3 brokers. Force eviction of any pod.

**Expected behavior**
I would expect that operator notices evicted pods and creates replacements.

**Additional context**
Observed with operator version 0.10.0 , kubernetes 1.15 on GKE.

### PR DESCRIPTION
**Pull request by baluchicken**
| Q               | A
| --------------- | ---
| Bug fix?        |yes|
| New feature?    | no|
| API breaks?     | no|
| Deprecations?   | no|
| Related tickets | fixes #326
| License         | Apache 2.0

### What's in this PR?

Without this fix the operator wont recognise an evicted pod. It leads to states where all broker pods are evicted and the operator does not restarts any of it.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

File: pkg/k8sutil/resource.go [hunk 1]
```diff
@@ -168,6 +168,14 @@ func IsPodContainsTerminatedContainer(pod *corev1.Pod) bool {
 	return false
 }
 
+// IsPodContainsEvictedContainer returns true if pod status has an evicted reason false otherwise
+func IsPodContainsEvictedContainer(pod *corev1.Pod) bool {
```
Comment (stoader) [inline pkg/k8sutil/resource.go:172]: Since `pod.Status.Reason` is not an enum I's use `strings.Contains(pod.Status.Reason, "Evicted")`

Comment (baluchicken) [reply pkg/k8sutil/resource.go:172]: Good point:)
