### PR TITLE
Use cluster namespace in cluster issuer name to make it unique

### LINKED ISSUE #372: ClusterIssuer shared between clusters
**Describe the bug**
Because ClusterIssuer is not a namespaced object, Kafka clusters with the same name generate the same ClusterIssuer object, in the format `{clustername}-issuer`, and end up colliding.

**Steps to reproduce the issue:**
Create a KafkaCluster named "kafka" in a namespace called "foo". Create a KafkaCluster named "kafka" in a namespace called "bar". Observe that both clusters attempt to share the cluster scoped ClusterIssuer named "kafka-issuer".

**Expected behavior**
I expected the KafkaClusters to be isolated from each other, not sharing an issuer. Because the ClusterIssuer is not a namespaced object, I expected the issuer to be uniquely named, perhaps including the namespace of the KafkaCluster as part of the name of the Clusterissuer.

**Screenshots**

**Additional context**
Kafka Operator v0.11.2

### PR DESCRIPTION
**Pull request by baluchicken**
| Q               | A
| --------------- | ---
| Bug fix?        |yes|
| New feature?    | no|
| API breaks?     | no|
| Deprecations?   | no|
| Related tickets | fixes #372
| License         | Apache 2.0

### What's in this PR?

This PR adds unique name to the generated ClusterIssuer. It is useful when you want to separate clusters from each other.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

File: pkg/util/pki/common.go [hunk 1]
```diff
@@ -153,14 +153,14 @@ func clusterDNSNames(cluster *v1beta1.KafkaCluster) (names []string) {
 }
 
 // LabelsForKafkaPKI returns kubernetes labels for a PKI object
-func LabelsForKafkaPKI(name string) map[string]string {
-	return map[string]string{"app": "kafka", "kafka_issuer": fmt.Sprintf(BrokerIssuerTemplate, name)}
+func LabelsForKafkaPKI(name, namespace string) map[string]string {
+	return map[string]string{"app": "kafka", "kafka_issuer": fmt.Sprintf(BrokerClusterIssuerTemplate, name, namespace)}
```
Comment (stoader) [inline pkg/util/pki/common.go:157]: I'd change the order to `namespace, name`.

Comment (baluchicken) [reply pkg/util/pki/common.go]: Fixed.

File: pkg/pki/certmanagerpki/certmanager_user.go [hunk 2]
```diff
@@ -206,8 +206,14 @@ func (c *certManager) getCA(user *v1alpha1.KafkaUser) (caName, caKind string) {
...
 	} else {
 		caKind = certv1.ClusterIssuerKind
-		caName = fmt.Sprintf(pkicommon.BrokerIssuerTemplate, c.cluster.Name)
+		caName = fmt.Sprintf(pkicommon.BrokerClusterIssuerTemplate,
+			c.cluster.Namespace, c.cluster.Name)
+	}
+	//Check if the new cluster issuer with namespaced name exists if not fall back to original one
+	var issuer *certv1.ClusterIssuer
+	err := c.client.Get(context.Background(), types.NamespacedName{Namespace: metav1.NamespaceAll, Name: caName}, issuer)
+	if err != nil && apierrors.IsNotFound(err) {
```
Comment (stoader) [inline pkg/pki/certmanagerpki/certmanager_user.go:215]: If the error is different from NotFound should that be returned upstream to trigger a reconcile?

Comment (baluchicken) [reply pkg/pki/certmanagerpki/certmanager_user.go:215]: No, since this code only creates certificates resource for cert-manager. If the used issuer is not available yet Cert manager will retry. On the other hand the issuer creation error is handled by the Kafka Operator. If something happens we are retrying that.

**Review by stoader — APPROVED** [review]

**Review by hi-im-aren — DISMISSED** [review]

**Review by stoader — APPROVED** [review]

**Review by chrisgacsal — APPROVED** [review]
LGTM! :shipit:
